config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  resources :users
  resource :session, only: [:new, :create, :destroy]
  resources :questions, except: [:show, :new, :index] do
    resources :hashtags, only: [:create, :destroy]
  end
  resources :hashtags, only: :show

end

app/models/hashtag.rb
class Hashtag < ActiveRecord::Base
  has_many :hashtag_questions
  has_many :questions, through: :hashtag_questions

  validates :text, presence: true

  scope :used_now, -> { joins(:hashtag_questions).distinct("hashtag.id") }
end

app/models/hashtag_question.rb
class HashtagQuestion < ActiveRecord::Base
  belongs_to :hashtag
  belongs_to :question

  validates :hashtag, :question, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  belongs_to :author, class_name: 'User'
  has_many :hashtag_questions, dependent: :destroy
  has_many :hashtags, through: :hashtag_questions

  validates :text, :user, presence: true
  validates :text, length: {maximum: 255}

  after_commit :update_question_hashtags, on: [:update, :create]

  def update_question_hashtags
    scanned_hashtags.each do |hsh|
      new_nashtag = Hashtag.find_or_create_by(text: hsh)
      HashtagQuestion.find_or_create_by(question: self, hashtag: new_nashtag)
    end

    self.hashtag_questions.each do |hsh|
      hsh.destroy! unless scanned_hashtags.include?(hsh.hashtag.text)
    end
  end

  def scanned_hashtags
    "#{text} #{answer}".scan(/\#[а-яА-Яa-zA-z\d-]+/).map(&:downcase).uniq
  end
end

app/models/user.rb
require 'openssl'

class User < ActiveRecord::Base
  #константы для работы метода шифрования пароля
  ITERATIONS = 2000
  DIGEST = OpenSSL::Digest::SHA256.new

  has_many :questions

  validates :email, :username, presence: true, uniqueness: true
  validates :password, presence: true, confirmation: true, on: :create
  validates :email, format: {with: /\A[a-zA-Z0-9_.\-]+@[a-zA-Z0-9\-]+\.[a-zA-Z0-9\-.]+\z/}
  validates :color, format: {with: /\A\#[\da-fA-Z]{6}\z/}
  validates :username, length: {maximum: 40}, format: {with: /\A[a-zA-z0-9_]+\z/}

  attr_accessor :password

  before_save :encrypt_password
  before_validation :lower_case
  before_validation :default_color

  def default_color
    self.color = '#005a55' if self.color.blank?
  end

  def lower_case
    self.username.downcase! unless username.nil?
  end

  def encrypt_password
    if self.password.present?
      #"соль" - рандомная строка усложняющая задачу хакерам
      self.password_salt = User.hash_to_string(OpenSSL::Random.random_bytes(16))

      #хеш пароля - уникальная строка
      self.password_hash = User.hash_to_string(
        OpenSSL::PKCS5.pbkdf2_hmac(self.password, self.password_salt, ITERATIONS, DIGEST.length, DIGEST)
      )
    end
  end

  def self.hash_to_string(password_hash)
    password_hash.unpack('H*')[0]
  end

  def self.authenticate(email, password)
    #надодим пользователя с email-ом из базы
    user = find_by(email: email)

    if user.present? && user.password_hash ==
      User.hash_to_string(
        OpenSSL::PKCS5.pbkdf2_hmac(password, user.password_salt, ITERATIONS, DIGEST.length, DIGEST)
      )
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def reject_user
    redirect_to root_path, alert: "Вам сюда низя!"
  end
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  def show
    @hashtag = Hashtag.find(params[:id])
    @questions = @hashtag.questions
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :load_question, only: [:show, :edit, :update, :destroy]
  before_action :autorize_user, except: [:create]

  def edit
  end

  def create
    @question = Question.new(question_params)

    @question.author = current_user

    if check_captcha(@question) && @question.save
      redirect_to user_path(@question.user), notice: 'Вопрос задан.'
    else
      render :edit
    end
  end

  def update
    if @question.update(question_params)

      redirect_to user_path(@question.user), notice: 'Вопрос сохранен.'
    else
      render :edit
    end
  end

  def destroy
    user = @question.user

    @question.destroy
    redirect_to user_path(user), notice: 'Вопрос удален.'
  end

  private

  def check_captcha(model)
    if current_user.present?
      true
    else
      verify_recaptcha(model: model)
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def load_question
    @question = Question.find(params[:id])
  end

  def autorize_user
    reject_user unless @question.user == current_user
  end

  def question_params
    if current_user.present? && params[:question][:user_id].to_i == current_user.id
      params.require(:question).permit(:user_id, :text, :answer)
    else
      params.require(:question).permit(:user_id, :text)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])

    if user.present?
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Вы успешно залогинились'
    else
      flash.now.alert = "Неправильный email или пароль"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Вы разлогинелись, приходите еще!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, except: [:index, :new, :create]
  before_action :autorize_user, except: [:index, :new, :create, :show]

  def index
    @users = User.all
    @hashtags = Hashtag.used_now
  end

  def new
    redirect_to root_url, alert: 'Вы уже залогинены' if current_user.present?
    @user = User.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'Данные обновлены!'
    else
      render 'edit'
    end
  end

  def create
    redirect_to root_url, alert: 'Вы уже залогинены' if current_user.present?
    @user = User.new(user_params)

    if @user.save
      redirect_to root_url, notice: 'Пользователь успешно зарегистрирован!'
      session[:user_id] = @user.id
    else
      render 'new'
    end
  end

  def show
    @questions = @user.questions.order(created_at: :desc)

    @new_question = @user.questions.build

    @questions_count = @questions.count
    @answers_count = @questions.where.not(answer: nil).count
    @unanswered_count = @questions_count - @answers_count
  end

  def destroy
    @user.destroy
    redirect_to root_path, notice: "Пользователь успешно удален! Приходите к нам еще!"
  end

  private

  def load_user
    @user = User.find(params[:id])
  end

  def autorize_user
    reject_user unless @user == current_user
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation,
                                 :name, :username, :avatar_url, :color)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_avatar(user)
    if user.avatar_url.present?
      user.avatar_url
    else
      asset_path 'avatar.png'
    end
  end

  def fa_icon(icon_class)
    content_tag 'span', '', class: "fa fa-#{icon_class}"
  end
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hashtags/_hashtag.html.erb
<span>
  <%= link_to hashtag.text, hashtag_path(hashtag), class: 'hashtag-small' %>
</span>

app/views/hashtags/show.html.erb
<div class="hashtag-title-content buffer-both text-center">
  <h1 class="text-lead">Все вопросы по хештегу <p class="hashtag-title"><%= @hashtag.text %></p></h1>
</div>
<%= render partial: 'questions/question', collection: @questions %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Хорошие вопросы</title>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="header">
  <div class="container">
    <div class="header-logo">
      <h1 class="header-title"><%= link_to "Хорошие вопросы", root_path %></h1>
    </div>

    <div class="header-nav">
      <% if current_user.present? %>
        <%= link_to "@#{current_user.username}", user_path(current_user) %>
        <%= link_to 'Выйти', session_path, data: {method: :delete} %>
      <% else %>
        <%= link_to 'Зарегистрироваться', new_user_path, class: 'button button-small button-light' %>
        <%= link_to 'Войти', new_session_path, class: 'button button-small button-light' %>
      <% end %>
    </div>
  </div>
</div>

<div class="content">
  <div class="container">
    <% if flash.any? %>
        <div class="content-wrapper buffer-both">
          <% flash.each do |name, message| %>
              <%= content_tag :div, message, class: "flash-#{name}" %>
          <% end %>
        </div>
    <% end %>
    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/questions/_form.html.erb
<div class="form">
  <%= form_for(@question) do |f| %>
      <% if @question.errors.any? %>
          <div class="form-errors">
            <ul>
              <% @question.errors.full_messages.each do |message| %>
                  <li class="form-error-message"><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <%= f.hidden_field :user_id %>

      <div class="form-field">
        <%= f.label :text, 'Вопрос', class: 'form-label' %>
        <%= f.text_area :text, class: 'form-textarea' %>
      </div>
      <% if current_user.present? && current_user == @question.user %>
          <div class="form-field">
            <%= f.label :answer, 'Ответ', class: 'form-label' %><br>
            <%= f.text_area :answer, class: 'form-textarea' %>
          </div>
      <% end %>

      <%= recaptcha_tags unless current_user.present? %>

      <div class="form-action buffer-both">
        <%= f.submit 'Сохранить', class: 'button button-dark button-small' %>
        или
        <%= link_to "Вернуться", user_path(@question.user) %>
      </div>
  <% end %>
</div>

app/views/questions/_question.html.erb
<%# Это фрагмет (паршал, partial) для вывода вопроса. В нем определена %>
<%# локальная переменная question, в которую при вызове будет передан %>
<%# как в метод ruby объект после ключа (object: @question) %>

<div class="question">
  <div class="question-content">
    <%# Текст вопроса %>
    <div class="question-text text-lead">
      <%= question.text %>
    </div>

    <%# Текст ответа, если он есть %>
    <% if question.answer %>
        <div class="question-answer text-lead">
          <%= question.answer %>
        </div>
    <% end %>

    <% if question.hashtags %>
        <div class="question-answer text-lead">
          <%= render partial: 'hashtags/hashtag', collection: question.hashtags, as: :hashtag %>
        </div>
    <% end %>

    <% if question.author %>
        <span class="text-small">Автор: </span>
        <%= link_to "@#{question.author.username}", user_path(question.author) %>
    <% end %>

    <%# Дата создания вопроса (отформатированная) %>
    <div class="question-date">
      <%= l(question.created_at, format: :short) %>
    </div>
  </div>

  <%# Если адресат вопроса — текущий пользователь, он может редактировать вопрос %>
  <%# и отвечать на него %>
  <% if question.user == current_user %>
      <%# Определяем какая будет иконка, если у вопроса нет ответа, то иконка %>
      <%# овтета на письмо, иначе — карандашик %>
      <% edit_icon = question.answer.blank? ? 'reply' : 'pencil' %>

      <div class="question-actions">
        <%= link_to fa_icon(edit_icon), edit_question_path(question) %>
        <%= link_to fa_icon('trash-o'), question_path(question),
                    method: :delete, data: {confirm: 'Точно удалить вопрос?'} %>
      </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Вопрос</h1>

  <div class="column-1-2">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Править профиль</h1>

  <div class="column-1-2">
    <div class="form">

      <% if @user.errors.any? %>
          <div class="form-errors">
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                  <li class="form-erros-message"><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <%= form_for @user do |f| %>

          <div class="form-field">
            <%= f.label 'Никнейм', class: 'form-label' %>
            <%= f.text_field :username, class: 'form-text-field' %>
          </div>

          <div class="form-field">
            <%= f.label 'Ваше имя', class: 'form-label' %>
            <%= f.text_field :name, class: 'form-text-field' %>
          </div>

          <div class="form-field">
            <%= f.label 'URL Вашей аватарки', class: 'form-label' %>
            <%= f.text_field :avatar_url, class: 'form-text-field' %>
          </div>

          <div class="form-action">
            <%= f.label 'Цвет фона', class: 'form-label' %>
            <%= f.color_field :color, value: @user.color, class: 'form-text-field' %>
          </div>

          <div class="buffer-top-large buffer-bottom">
            Если не хотите менять пароль - оставьте поля пустыми!
          </div>

          <div class="form-field">
            <%= f.label :password, class: 'form-label' %>
            <%= f.password_field :password, class: 'form-text-field' %>
          </div>

          <div class="form-field">
            <%= f.label :password_confirmation, 'Пароль еще раз', class: 'form-label' %>
            <%= f.password_field :password_confirmation, class: 'form-text-field' %>
          </div>

          <div class="form-action">
            <%= f.submit 'Сохранить', class: 'button button-small button-dark' %>
          </div>

          <div class="form-action">
            <%= link_to 'Удалить аккаунт', @user, method: 'delete',
                        data: { confirm: "Вы уверены, что хотите удалить свой аккаунт?" },
                        class: 'button button-small button-red' %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<%# Этот шаблон отрисуется, когда посетитель захочет посмотреть список %>
<%# пользователей на странице /users (users#index) %>
<div class="content-wrapper buffer-both text-center">
  <div class="buffer-both">
    <h1 class="title-medium">Наши пользователи</h1>
  </div>

  <%# Этот код выводит каждого пользователя в цикле %>
  <% @users.each do |user| %>
      <div class="users-list-item">
        <div class="user-image-div user-image-div-small">
          <%# Пользуемся аж четырьмя хелперами: %>
          <%# * link_to — генерирует ссылку %>
          <%# * image_tag — генерирует картинку %>
          <%# * user_avatar — достает из пользователя ссылку на картинку %>
          <%#   или подставляет дефолтную %>
          <%# * user_path(user) возвращает относительный путь страницы %>
          <%#   пользователя, например /users/1 %>
          <%= link_to image_tag(user_avatar(user), class: 'user-image'), user_path(user) %>
        </div>
      </div>
  <% end %>
</div>

<div class="content-wrapper buffer-both">
  <div class="buffer-both text-center">
    <h1 class="title-medium">Все хештеги</h1>
  </div>
  <div>
    <%= render partial: 'hashtags/hashtag', collection: @hashtags %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Присоединяйся к нам!</h1>

  <div class="column-1-2">
    <div class="form">
      <% if @user.errors.any? %>
          <div class="form-errors">
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                  <li class="form-erros-message"><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <%= form_for @user do |f| %>
          <div class="form-field">
            <%= f.label :email, 'Логин (email)', class: 'form-label' %>
            <%= f.text_field :email, class: 'form-text-field' %>
          </div>

          <div class="form-field">
            <%= f.label :username, 'Никнейм', class: 'form-label' %>
            <%= f.text_field :username, class: 'form-text-field' %>
          </div>

          <div class="form-field">
            <%= f.label :name, 'Имя', class: 'form-label' %>
            <%= f.text_field :name, class: 'form-text-field' %>
          </div>

          <div class="form-field">
            <%= f.label :password, 'Пароль', class: 'form-label' %>
            <%= f.password_field :password, class: 'form-text-field' %>
          </div>

          <div class="form-field">
            <%= f.label :password_confirmation, 'Пароль еще раз', class: 'form-label' %>
            <%= f.password_field :password_confirmation, class: 'form-text-field' %>
          </div>

          <div class="form-field">
            <%= f.submit 'Зарегистрироваться', class: 'button button-small button-dark' %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-header text-center" style="background: <%= "#{@user.color}" %>">

  <h1 class="title-medium">
    <%= @user.name %>
  </h1>

  <div class="buffer-both">
    <%= link_to 'Редактировать профиль', edit_user_path(@user) if current_user == @user %>
  </div>

  <div class="user-image-div">
    <%= image_tag user_avatar(@user), class: 'user-image', alt: '[Фото]' %>
  </div>

  <h2 class="title-small buffer-both">
    @<%= @user.username %>
  </h2>
</div>

<div class="user-details">
  <div class="user-ask-button container text-center">
    <%= link_to "Спроси меня", '', class: 'button button-light', id: 'ask-button' %>
  </div>

  <%# Выводим счетчики вопросов в три колонки. Обратите внимание, что тут %>
  <%# в пору использовать наш любимый склонятор. На эту тему смотрите ДЗ. %>
  <div class="user-statistics container text-center">
    <div class="column-1-3">
      <h1 class="title-small"><%= @questions_count %></h1>
      <p><%= t('questions', count: @questions_count) %></p>
    </div>
    <div class="column-1-3">
      <h1 class="title-small"><%= @answers_count %></h1>
      <p><%= t('answers', count: @answers_count) %></p>
    </div>
    <div class="column-1-3">
      <h1 class="title-small"><%= @unanswered_count %></h1>
      <p><%= t('unanswered', count: @unanswered_count) %></p>
    </div>
  </div>
</div>

<div class="user-question-form-div column-1-4 column-1-4-right" id='ask-form'>
  <div class="user-question-form buffer-both">
    <%= form_for @new_question do |f| %>
        <%= f.hidden_field :user_id %>

        <div class="form-field">
          <%= f.label "Ваш вопрос для @#{@user.username}", class: 'form-label' %>
          <%= f.text_area :text, class: 'form-textarea' %>
        </div>

        <%= recaptcha_tags size: 'compact' unless current_user.present? %>

        <div class="form-action">
          <%= submit_tag 'Задать вопрос', class: 'button button-small button-dark' %>
        </div>
    <% end %>
  </div>
</div>

<div class="column-3-4">
  <div class="user-questions buffer-both">
    <div class="questions-list">
      <% @questions.each do |question| %>
          <%= render partial: 'questions/question', object: question %>
      <% end %>
    </div>
  </div>
</div>